### ISSUE TITLE
Failed to launch a grid node

### ISSUE THREAD

**Issue by bobsonlin26** [OpenMined/GridNode#10]
## Describe Bug
Cannot launch a grid node because in `syft.generic.object_storage` ObjectStorage is renamed to ObjectStore
## Reproduce
```
$ git clone https://github.com/OpenMined/GridNode.git
$ git clone https://github.com/OpenMined/PySyft.git
$ cd GridNode/
$ pip install -r requirement
$ cd ../PySyft/
$ pip install -e .
$ cd ../GridNode/
$ python grid_node.py --host 0.0.0.0 --port 5540 --id 0
```
## Screenshot
![aa](https://user-images.githubusercontent.com/63451786/82156967-2e33c700-98b1-11ea-86f3-a7c41b3a3019.png)

**Comment by IonesioJunior** [comment]
@bobsonlin26 Could you confirm if this issue was solved by your previous PR's?

**Comment by bobsonlin26** [comment]
@IonesioJunior Yeah, it was solved !
