### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/GridNode#12]
[Based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md), we should improve our readmes across all OpenMined projects.

[Please consult the following document for our desired best practices.](https://docs.google.com/document/d/126smq1Gful_mo-x5Wm1M1UJW9CvB8fT9YYZmamNqk0M/edit?usp=sharing)

**Comment by jmaunon** [comment]
I will try to work on this

**Comment by cereallarceny** [comment]
Great! @em-blue will be in touch with you.

**Comment by IonesioJunior** [comment]
Solved by #13
