### ISSUE TITLE
Failed to use "fix precision" to the remote tensor

### ISSUE THREAD

**Issue by bobsonlin26** [OpenMined/GridNode#6]
According to [Part 10 - Federated Learning with Secure Aggregation.ipynb](https://github.com/OpenMined/PySyft/blob/master/examples/tutorials/Part%2010%20-%20Federated%20Learning%20with%20Secure%20Aggregation.ipynb), when trying secure aggregation, it must use "fix precision" to the tensor that is stored in the remote worker.
But since worker cannot recognize itself, this operation will fail.
```
# General dependencies
import torch as th
import syft as sy
from syft.grid.public_grid import PublicGridNetwork
from syft.grid.private_grid import PrivateGridNetwork
from syft.workers.node_client import NodeClient
hook = sy.TorchHook(th)
# WARNING: We should use the same id and port as the one used to start the app!!!
alice = NodeClient(hook, "ws://localhost:3000", id="alice")
# If you don't connect to the worker you can't send messages to it
alice.connect()
num = th.tensor([0.123, 2.345, 3.456])
p_num = num.send(alice)
fpn = p_num.fix_precision()
print("success")
```

**Comment by bobsonlin26** [comment]
I found a workaround that add `local_worker.add_worker(hook.local_worker)` in the `GridNode/app/__init__.py`
I'm not sure is it ok to create a PR based on this way...
![code](https://user-images.githubusercontent.com/63451786/79071399-1f844e00-7d0e-11ea-8541-c49131dbbfd7.png)

**Comment by IonesioJunior** [comment]
Yep, It seems reasonable! Please, go ahead, I'm looking forward to merge it! :rocket:
